agent:
  mode: 'flow'
  configMap:
    content: |
      prometheus.remote_write "default" {
        endpoint {
          url = "YOUR_PROMETHEUS_URL"
          basic_auth {
            username = "YOUR_USERNAME"
            password = "YOUR_API_KEY"
          }
        }
      }
      
      prometheus.scrape "default" {
        targets = [{"__address__" = "localhost:9090"}]
        forward_to = [prometheus.remote_write.default.receiver]
      }
