services:
  - type: web
    name: grafana-banking-dashboard
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: GF_SECURITY_ADMIN_PASSWORD
        generateValue: true
      - key: GF_SERVER_ROOT_URL
        value: https://grafana-banking-dashboard.onrender.com
      - key: GF_SECURITY_ADMIN_USER
        value: admin
      - key: GF_INSTALL_PLUGINS
        value: ""
